title: Cosmic Canvas
description: A collaborative fantasy world—gods, realms, nations, factions, and myths.
url: https://triursa.github.io
baseurl: /cosmic_canvas

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: 

# Just the Docs settings
search_enabled: true
back_to_top: true
back_to_top_text: "Back to top"
aux_links:
  "Mural (World Canvas)":
    - "https://app.mural.co/t/digitallotus9965/m/digitallotus9965/1746272006278/ba82f868f204fb732a84d435aeb6b27ae6fb4838"
aux_links_new_tab: true

# Navigation order is controlled via front matter nav_order on each page.
nav_external_links:
  - title: Source on GitHub
    url: https://github.com/triursa/cosmic_canvas

# Build
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# Optional: sitemap
kramdown:
  input: GFM
footer_content: "Cosmic Canvas • Built with Just the Docs"
